services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo           # aquí debe existir odoo.conf
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db                      # opcional
      - TZ=Europe/Madrid
    secrets:
      - postgresql_password

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: odoo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: odoo
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: postgresql_password
