services:
  web:
    image: nginx:alpine
    container_name: nginx-web
    ports:
      - "8080:80"            # visit http://localhost:8080
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
