services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "1000:1000"                  # tu UID:GID
    ports:
      - "8096:8096"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    restart: unless-stopped
